name: Kwiki-DB
version: 0.02
abstract: DBI access for Kwiki plugin writers
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  DBD::SQLite: 0
requires:
  Kwiki: 0.38
  DBI: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
